export default (theme) => ({
  wrapper: {
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  paper: {
    height: '70%',
    width: '60%',
    display: 'inline-block',
    textAlign: 'left',
    boxSizing: 'border-box',
    padding: theme.spacing.unit * 8,
    paddingTop: theme.spacing.unit * 4,
    paddingBottom: theme.spacing.unit * 4,
  },
  toolbar: {
    height: '70%',
    width: '20%',
    display: 'inline-block',
    textAlign: 'left',
    boxSizing: 'border-box',
    padding: theme.spacing.unit * 8,
    paddingTop: theme.spacing.unit * 4,
    paddingBottom: theme.spacing.unit * 4,
    marginLeft: '5%',
  },
});
